### ISSUE TITLE
Could you please upload the train.prototxt of the model?

### ISSUE THREAD

**Issue by CSUDaXiang** [SpyderXu/ssd_sort#3]
Thanks for your sharing,it is a very good job，and I want to learn more about this project,but I can't find the train.prototxt,so can you upload this file?Thanks a lot!

**Comment by SpyderXu** [comment]
The train.prototxt and solver.prototxt have been upload under the model file. To train your own model you should install SSD detector.

**Comment by CSUDaXiang** [comment]
Thank you very much for your sharing,I have installed SSD detector as you said in the README.md.
